// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeQ1GL-jnSZ7xnYtf_4c0SBWBTTKy5GKM',
    appId: '1:870535581359:web:912e9660fdd4e244e34e5a',
    messagingSenderId: '870535581359',
    projectId: 'hastane-otomasyonu-2214a',
    authDomain: 'hastane-otomasyonu-2214a.firebaseapp.com',
    storageBucket: 'hastane-otomasyonu-2214a.appspot.com',
    measurementId: 'G-LXCLK37VRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS62naiBnQHoBZVtmLdzSCzDtkg_ddJqI',
    appId: '1:870535581359:android:5e8a7d6d796de271e34e5a',
    messagingSenderId: '870535581359',
    projectId: 'hastane-otomasyonu-2214a',
    storageBucket: 'hastane-otomasyonu-2214a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUACzLQT8_ZwgRfQ7WdkJ4sW41OJcSYsM',
    appId: '1:870535581359:ios:9525d9ff7b9c3979e34e5a',
    messagingSenderId: '870535581359',
    projectId: 'hastane-otomasyonu-2214a',
    storageBucket: 'hastane-otomasyonu-2214a.appspot.com',
    iosBundleId: 'com.example.hastaneOtomasyonu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUACzLQT8_ZwgRfQ7WdkJ4sW41OJcSYsM',
    appId: '1:870535581359:ios:9525d9ff7b9c3979e34e5a',
    messagingSenderId: '870535581359',
    projectId: 'hastane-otomasyonu-2214a',
    storageBucket: 'hastane-otomasyonu-2214a.appspot.com',
    iosBundleId: 'com.example.hastaneOtomasyonu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeQ1GL-jnSZ7xnYtf_4c0SBWBTTKy5GKM',
    appId: '1:870535581359:web:f2cf31cc93f833f2e34e5a',
    messagingSenderId: '870535581359',
    projectId: 'hastane-otomasyonu-2214a',
    authDomain: 'hastane-otomasyonu-2214a.firebaseapp.com',
    storageBucket: 'hastane-otomasyonu-2214a.appspot.com',
    measurementId: 'G-V0837R699R',
  );
}
